name: Build and Deploy to Pages
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 10 * * *' # 3am PDT / 2am PST daily
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm' # Speeds up future runs

      - name: Install and Build
        run: |
          npm ci        # Cleaner install than 'npm install' for CI
          npm run build # Generates your static files (e.g., in /dist or /build)

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./out # Change this to your build output folder (e.g., 'build' or 'public')

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
